FROM python:3.12-slim
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
COPY user_service /app/user_service
EXPOSE 8002
CMD ["uvicorn", "user_service.main:app", "--host", "0.0.0.0", "--port", "8002"]